export default{
    USER_REQUEST : "DEMO_REQUESTING",
    USER_SUCCESS : "USER_SUCCESS",
    USER_FAIL : "USER_FAIL",
    USER_GET_ARR_USER: "USER_GET_ARR_USER",
    USER_GET_USER: "USER_GET_USER",
}
